### ISSUE TITLE
pdf-tools fails to compile on 10.4.1

### ISSUE THREAD

**Issue by BenWibking** [dunn/homebrew-emacs#754]
Running 10.4.1, I get:

```
$ brew install pdf-tools --HEAD
Cannot read termcap database;
using dumb terminal settings.
==> Installing pdf-tools from dunn/emacs
Cannot read termcap database;
using dumb terminal settings.
==> Cloning https://github.com/politza/pdf-tools.git
Updating /Users/benwibking/Library/Caches/Homebrew/pdf-tools--git
==> Checking out branch master
Already on 'master'
Your branch is up to date with 'origin/master'.
HEAD is now at b6c0e4f Fix indentation
==> make server/epdfinfo
Last 15 lines from /Users/benwibking/Library/Logs/Homebrew/pdf-tools/01.make:
  "_synctex_node_tag", referenced from:
      _cmd_synctex_backward_search in epdfinfo-epdfinfo.o
  "_synctex_scanner_free", referenced from:
      _cmd_synctex_forward_search in epdfinfo-epdfinfo.o
      _cmd_synctex_backward_search in epdfinfo-epdfinfo.o
  "_synctex_scanner_get_name", referenced from:
      _cmd_synctex_backward_search in epdfinfo-epdfinfo.o
  "_synctex_scanner_new_with_output_file", referenced from:
      _cmd_synctex_forward_search in epdfinfo-epdfinfo.o
      _cmd_synctex_backward_search in epdfinfo-epdfinfo.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [epdfinfo] Error 1
make[1]: *** [all] Error 2
make: *** [server/epdfinfo] Error 2

If reporting this issue please do so at (not Homebrew/brew or Homebrew/core):
https://github.com/dunn/homebrew-emacs/issues

```

**Comment by BenWibking** [comment]
`brew doctor` shows:

```
$brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: You have unlinked kegs in your Cellar
Leaving kegs unlinked can lead to build-trouble and cause brews that depend on
those kegs to fail to run properly once built. Run `brew link` on these:
  pyqt
```

**Comment by BenWibking** [comment]
As you can see from above, that's what I tried but it doesn't work for me.

**Comment by dunn** [comment]
Ah, sorry.  Can you post `brew gist-logs pdf-tools` so I can see what the full error was?

**Comment by BenWibking** [comment]
Here's the full error: https://gist.github.com/0194d4dfffa2e4292ad01503ef4a26e2

**Comment by dunn** [comment]
Looks like it's this: https://github.com/politza/pdf-tools/issues/443

Possibly it's succeeding for me since I have a LaTeX installation.

When I get the time I'll try to figure out how to set the correct env variables.  If you figure it out first, thought, please open a PR!

**Comment by schoukah** [comment]
exact same issue as OP for me. Also tried with `brew install pdf-tools --HEAD`. Though I'm still running on 10.13.

**Comment by vemv** [comment]
What are the exact env-value pairs that I have to set?
